export const qk = {
  me: ["auth", "me"] as const,
  popularRoutes: ["public", "popular-routes"] as const,
  airports: (q: string) => ["public", "airports", q] as const,
  flightSearch: (payload: unknown) => ["public", "flight-search", payload] as const,
  myRequests: (params: unknown) => ["booking-requests", "mine", params] as const,
  request: (reference: string, email?: string) => ["booking-requests", reference, email] as const,
  messages: (reference: string) => ["messages", reference] as const,
  paymentMethods: (country: string, currency: string) => ["payments", "methods", country, currency] as const,
  payment: (reference: string) => ["payments", reference] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  adminRequests: (params: unknown) => ["admin", "requests", params] as const,
  adminRequest: (reference: string) => ["admin", "request", reference] as const,
  adminBookings: (params: unknown) => ["admin", "bookings", params] as const,
  adminBooking: (reference: string) => ["admin", "booking", reference] as const,
  adminCustomers: (params: unknown) => ["admin", "customers", params] as const,
  adminCustomer: (id: string) => ["admin", "customer", id] as const,
  adminEnquiries: (params: unknown) => ["admin", "enquiries", params] as const,
  adminUsers: (params: unknown) => ["admin", "users", params] as const,
  adminUnread: ["admin", "unread"] as const,
};
