import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle, Mail, MessageSquareText, Send } from "lucide-react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { publicService } from "@/api/services";
import { FieldError } from "@/components/ui";
import { useToastStore } from "@/store/toast";
import { getErrorMessage } from "@/api/client";
const schema=z.object({name:z.string().min(2),email:z.email(),phone:z.string().min(8),subject:z.string().min(4),message:z.string().min(20).max(2000)});type Form=z.infer<typeof schema>;
export function ContactPage(){const push=useToastStore(s=>s.push);const form=useForm<Form>({resolver:zodResolver(schema),defaultValues:{name:"",email:"",phone:"",subject:"",message:""}});const submit=async(v:Form)=>{try{const r=await publicService.enquiry({...v,source:"landing"});push(r.message||"Enquiry sent");form.reset();}catch(e){push(getErrorMessage(e),"error")}};return <main className="page-shell py-14"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-[2.5rem] bg-[#102e62] p-8 text-white sm:p-10"><p className="eyebrow !text-blue-300">Travel support</p><h1 className="mt-4 font-display text-4xl font-extrabold tracking-[-.04em]">Tell us what your itinerary needs.</h1><p className="mt-4 text-sm leading-7 text-blue-100/70">Use this form for group travel, complex routes, date flexibility, or booking questions that need an operations specialist.</p><div className="mt-10 space-y-5"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><MessageSquareText className="h-5 w-5"/></span><div><strong className="block">Stored in the admin inbox</strong><span className="text-sm text-blue-100/60">Your enquiry has a tracked status and response record.</span></div></div><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Mail className="h-5 w-5"/></span><div><strong className="block">Email response</strong><span className="text-sm text-blue-100/60">Replies are delivered using the backend notification provider.</span></div></div></div></section><form className="surface p-7 sm:p-9" onSubmit={form.handleSubmit(submit)}><h2 className="font-display text-2xl font-extrabold text-slate-900">Send an enquiry</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><div><label className="label">Name</label><input className="field" {...form.register("name")}/><FieldError message={form.formState.errors.name?.message}/></div><div><label className="label">Email</label><input className="field" type="email" {...form.register("email")}/><FieldError message={form.formState.errors.email?.message}/></div><div><label className="label">Phone</label><input className="field" {...form.register("phone")}/><FieldError message={form.formState.errors.phone?.message}/></div><div><label className="label">Subject</label><input className="field" {...form.register("subject")}/><FieldError message={form.formState.errors.subject?.message}/></div><div className="sm:col-span-2"><label className="label">Message</label><textarea className="textarea min-h-40" {...form.register("message")}/><FieldError message={form.formState.errors.message?.message}/></div></div><button className="btn-primary mt-6" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}Send enquiry</button></form></div></main>;}
