import { SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { FlightSearchForm } from "@/components/FlightSearchForm";
import { FlightCard } from "@/components/FlightCard";
import { EmptyState, ErrorState, InlineLoader } from "@/components/ui";
import { useFlightSearch } from "@/query/hooks";
import { useBookingDraftStore } from "@/store/bookingDraft";
import type { SearchFlightsPayload } from "@/types/api";

export function SearchPage() { const location=useLocation(); const navigate=useNavigate(); const initial=(location.state as {payload?:SearchFlightsPayload}|null)?.payload||null; const [payload,setPayload]=useState<SearchFlightsPayload|null>(initial?.segments[0]?.departureDate?initial:null); const [stops,setStops]=useState("all"); const results=useFlightSearch(payload); const setDraft=useBookingDraftStore(s=>s.setDraft); const offers=useMemo(()=>{const all=results.data?.data.offers||[]; return stops==="all"?all:all.filter(o=>(o.slices[0]?.stops||0)===(stops==="direct"?0:1));},[results.data,stops]); const select=(offer:typeof offers[number])=>{if(!payload)return;setDraft(offer,payload);navigate("/booking/new");}; return <main className="page-shell py-10"><div><p className="eyebrow">Flight search</p><h1 className="mt-2 font-display text-4xl font-extrabold tracking-[-.04em] text-slate-900">Compare available offers.</h1><p className="mt-2 text-sm text-slate-500">Fares and availability come directly from the configured backend provider.</p></div><div className="mt-7"><FlightSearchForm initial={payload || initial} onSearch={setPayload} compact/></div>{payload?<div className="mt-9 grid gap-7 lg:grid-cols-[230px_1fr]"><aside className="surface h-fit p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-blue-800"/><h2 className="font-display font-extrabold text-slate-900">Filters</h2></div><label className="label mt-6">Stops</label><select className="field" value={stops} onChange={e=>setStops(e.target.value)}><option value="all">Any stops</option><option value="direct">Nonstop only</option><option value="one">Up to 1 stop</option></select><p className="mt-5 text-xs leading-5 text-slate-400">Final fare, ticketing rules, and availability are revalidated before confirmation.</p></aside><section>{results.isPending?<InlineLoader label="Searching flight inventory"/>:results.isError?<ErrorState error={results.error} onRetry={()=>results.refetch()}/>:offers.length?<div className="space-y-5"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-500"><strong className="text-slate-900">{offers.length}</strong> offers found</p></div>{offers.map(offer=><FlightCard key={offer.offerId} offer={offer} onSelect={()=>select(offer)}/>)}</div>:<EmptyState title="No offers found" description="Try different travel dates, nearby airports, or another cabin class."/>}</section></div>:<div className="mt-10"><EmptyState title="Choose your route" description="Enter airports and dates above to load real flight offers from the API."/></div>}</main>; }
