import { MapPin, Search } from "lucide-react";
import { useDeferredValue, useState } from "react";
import { useAirportSearch } from "@/query/hooks";
import type { Airport } from "@/types/api";

export function AirportAutocomplete({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (iata: string, airport?: Airport) => void; placeholder: string }) {
  const [query, setQuery] = useState(value); const [open, setOpen] = useState(false); const deferred = useDeferredValue(query); const results = useAirportSearch(deferred);
  const select = (airport: Airport) => { setQuery(`${airport.city} (${airport.iata})`); onChange(airport.iata, airport); setOpen(false); };
  return <div className="relative"><label className="label">{label}</label><div className="relative"><MapPin className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-blue-700"/><input className="field pl-11" value={query} placeholder={placeholder} autoComplete="off" onFocus={() => setOpen(true)} onChange={(e) => { setQuery(e.target.value); onChange(e.target.value.toUpperCase().slice(0,3)); setOpen(true); }} /></div>{open && deferred.trim().length >= 2 ? <div className="absolute z-30 mt-2 max-h-72 w-full overflow-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">{results.isFetching ? <div className="flex items-center gap-2 px-3 py-4 text-sm text-slate-500"><Search className="h-4 w-4 animate-pulse" />Searching airports</div> : (results.data?.data.airports || []).length ? results.data!.data.airports.map((airport) => <button type="button" key={airport.iata} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-blue-50" onClick={() => select(airport)}><span className="grid h-9 w-12 place-items-center rounded-lg bg-blue-50 text-xs font-extrabold text-blue-800">{airport.iata}</span><span><strong className="block text-sm text-slate-900">{airport.city} · {airport.name}</strong><span className="text-xs text-slate-500">{airport.country}</span></span></button>) : <p className="px-3 py-4 text-sm text-slate-500">No airports found.</p>}</div> : null}</div>;
}
