import type { ReactNode } from "react";
import { AlertCircle, LoaderCircle, SearchX } from "lucide-react";
import { getErrorMessage } from "@/api/client";

export function FullPageLoader({ label = "Loading" }: { label?: string }) { return <div className="grid min-h-[55vh] place-items-center"><div className="flex items-center gap-3 text-sm font-semibold text-slate-500"><LoaderCircle className="h-5 w-5 animate-spin text-blue-700" />{label}</div></div>; }
export function InlineLoader({ label = "Loading" }: { label?: string }) { return <div className="flex items-center justify-center gap-2 py-10 text-sm font-semibold text-slate-500"><LoaderCircle className="h-4 w-4 animate-spin" />{label}</div>; }
export function ErrorState({ error, onRetry }: { error: unknown; onRetry?: () => void }) { return <div className="surface-soft p-7 text-center"><AlertCircle className="mx-auto h-8 w-8 text-rose-500" /><h3 className="mt-3 font-display text-lg font-bold text-slate-900">Unable to load this information</h3><p className="mx-auto mt-2 max-w-xl text-sm text-slate-600">{getErrorMessage(error)}</p>{onRetry ? <button className="btn-secondary mt-5" onClick={onRetry}>Try again</button> : null}</div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="surface-soft p-10 text-center"><SearchX className="mx-auto h-8 w-8 text-slate-400" /><h3 className="mt-3 font-display text-lg font-bold text-slate-900">{title}</h3><p className="mx-auto mt-2 max-w-xl text-sm text-slate-600">{description}</p>{action ? <div className="mt-5">{action}</div> : null}</div>; }
export function Pagination({ page, totalPages, onPage }: { page: number; totalPages: number; onPage: (page: number) => void }) { if (totalPages <= 1) return null; return <div className="flex items-center justify-end gap-3 pt-5"><button className="btn-secondary min-h-9 px-4" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><span className="text-sm font-semibold text-slate-500">Page {page} of {totalPages}</span><button className="btn-secondary min-h-9 px-4" disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next</button></div>; }
export function FieldError({ message }: { message?: string }) { return message ? <p className="mt-1 text-xs font-semibold text-rose-600">{message}</p> : null; }
